# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SenseRemoteDetection
                                 A QGIS plugin
 AI detection algorithms for remote sensing images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-21
        copyright            : (C) 2022 by atlas@SenseTime
        email                : xuxiang@sensetime.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'atlas@SenseTime'
__date__ = '2022-09-21'
__copyright__ = '(C) 2022 by atlas@SenseTime'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SenseRemoteDetection class from file SenseRemoteDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sense_detection import SenseRemoteDetectionPlugin
    return SenseRemoteDetectionPlugin()
